Edit pip-compile command in base.txt
kpi-web-guild/django-girls-blog-OlenaEfymenko pull request #32
Opened 2023-12-26 23:08 UTC by OlenaYefymenko

2023-12-26 23:19 UTC, webknjaz requested changes
7 files changed.

2023-12-27 11:32 UTC, webknjaz requested changes
I'll wait to see the commit/PR message that refers to something useful instead of pointing to a generic action with an unspecified effect.

2023-12-27 12:13 UTC, OlenaYefymenko commented
> I'll wait to see the commit/PR message that refers to something useful instead of pointing to a generic action with an unspecified effect.

Yes, I agree. Edited.

2023-12-27 13:30 UTC, webknjaz approved these changes

2023-12-27 14:11 UTC, merged