Integrate Codecov code coverage reporting
kpi-web-guild/django-girls-blog-OlenaEfymenko pull request #34
Opened 2024-01-09 12:09 UTC by OlenaYefymenko

This patch adds powerful tool to automatically track test coverage across branches and pull requests. Codecov displays the overall coverage percentage and highlights gaps in test cases for each code change.

Related #18

2024-01-09 12:14 UTC, webknjaz commented
> This patch adds powerful tool to automatically track test coverage across branches and pull requests.

Is this an advertisement by ChatGPT?

2024-01-09 12:54 UTC, OlenaYefymenko commented
> > This patch adds powerful tool to automatically track test coverage across branches and pull requests.
> 
> Is this an advertisement by ChatGPT?

To be honest, the idea is mine🙂. I just check the grammar sometimes. I had doubts about the word "powerful". I have confusion when I try to add a description without making it sound like an advertisement.

2024-01-09 18:42 UTC, webknjaz requested changes
This won't work in the linters job since it doesn't produce any coverage report files. You should collect coverage from the test runs instead.

2024-01-09 20:00 UTC, OlenaYefymenko commented
> This won't work in the linters job since it doesn't produce any coverage report files. You should collect coverage from the test runs instead.

Sorry for being inattentive.

2024-01-10 02:03 UTC, webknjaz commented
In the CI log, the upload step doesn't find `coverage.xml`. Is it getting created locally? You could temporarily inject an extra step with something like `ls -l` after running the tests in CI, to see what files are present in the directory in the job.

2024-01-10 14:34 UTC, OlenaYefymenko commented
> In the CI log, the upload step doesn't find `coverage.xml`. Is it getting created locally? You could temporarily inject an extra step with something like `ls -l` after running the tests in CI, to see what files are present in the directory in the job.

Initially, there was no local file. Then I ran `python -m coverage run manage.py test`. Now, in the repository, I have the `coverage.xml` file. However, when running tests, I noticed the following issue:

```
  Codecov report uploader 0.7.1
[2024-01-10T13:10:30.878Z] ['info'] => Project root located at: /home/runner/work/django-girls-blog-OlenaEfymenko/django-girls-blog-OlenaEfymenko
[2024-01-10T13:10:30.879Z] ['info'] ->  Token found by environment variables
[2024-01-10T13:10:30.979Z] ['info'] Running coverage xml...
[2024-01-10T13:10:31.065Z] ['info'] Searching for coverage files...
[2024-01-10T13:10:31.088Z] ['info'] Warning: Some files located via search were excluded from upload.
[2024-01-10T13:10:31.088Z] ['info'] If Codecov did not locate your files, please review https://docs.codecov.com/docs/supported-report-formats
[2024-01-10T13:10:31.088Z] ['error'] There was an error running the uploader: No coverage files located, please try use `-f`, or change the project root with `-R`
```

Maybe it's because I don't have tests yet. Is that the reason?

2024-01-10 22:52 UTC, webknjaz commented
No, the step you added shows that file in the list. Perhaps, you need to point to it explicitly through `with:`.

You can also save it as an artifact in CI so you'd be able to download it after the workflow run.

2024-01-11 19:00 UTC, OlenaYefymenko commented
> No, the step you added shows that file in the list. Perhaps, you need to point to it explicitly through `with:`.
> 
> You can also save it as an artifact in CI so you'd be able to download it after the workflow run.

Finally, It's works :)

2024-01-11 19:34 UTC, webknjaz commented on .github/workflows/ci.yml
> +        files: ./coverage.xml
Let's keep the inputs ordered:
```suggestion
        files: coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
```

2024-01-11 19:35 UTC, webknjaz commented
Interesting.. I'd expect the auto-discovery mechanism to find this file. This might be a bug in the Codecov action. OTOH, this is fine for now.

2024-01-14 00:06 UTC, webknjaz approved these changes

2024-01-14 09:26 UTC, merged

2024-12-09 17:37 UTC, webknjaz commented on .github/workflows/ci.yml
> +      uses: codecov/codecov-action@v3
There's v5 of the action now.