🧩Upgrade the dependencies for the project
kpi-web-guild/django-girls-blog-OlenaEfymenko pull request #45
Opened 2024-12-29 23:22 UTC by OlenaYefymenko

This patch updates the development environment to Python 3.12.0 and all
    project dependencies accordingly

2024-12-29 23:28 UTC, OlenaYefymenko commented on .gitignore
The changes to .gitignore look strange, I only uncommented `.python-version`. The task was to switch to Python 3.12.0.

2024-12-30 00:08 UTC, webknjaz commented on .gitignore
It shouldn't be committed to Git anyway.

2024-12-30 00:10 UTC, webknjaz requested changes
The CI config must match the new dev env version. And the gitignore changes are fully out of the scope.

2025-01-02 22:47 UTC, OlenaYefymenko commented
> The CI config must match the new dev env version. And the gitignore changes are fully out of the scope.

Yep, thank you, I added 3.12 version in `ci.yml` also

2025-01-02 23:34 UTC, OlenaYefymenko commented on .gitignore
Removed

2025-01-03 02:32 UTC, webknjaz approved these changes

2025-01-03 10:24 UTC, merged